// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main-page': string;
  'product-item': string;
  'product-item__title': string;
}
export const cssExports: CssExports;
export default cssExports;
