// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'product': string;
  'product-buttons': string;
  'product-buttons__amount': string;
  'product-buttons__price': string;
  'product-content': string;
  'product-image': string;
  'product-remove': string;
  'product-text': string;
  'product-text__description': string;
  'product-text__title': string;
}
export const cssExports: CssExports;
export default cssExports;
