// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'amount-counter': string;
  'footer': string;
  'order': string;
  'price-counter': string;
  'result': string;
  'result__amount': string;
  'result__price': string;
  'return': string;
}
export const cssExports: CssExports;
export default cssExports;
