// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header-title': string;
  'header-title__content': string;
  'header-title__title': string;
}
export const cssExports: CssExports;
export default cssExports;
