// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'interaction': string;
  'interaction__add': string;
  'interaction__counter': string;
  'interaction__counter_hidden': string;
  'interaction__price': string;
  'interaction__result': string;
}
export const cssExports: CssExports;
export default cssExports;
