// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'upload-content': string;
  'upload-content_hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
