// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'nav-basket-button': string;
  'nav-basket-button__amount': string;
  'nav-basket-button__arrow': string;
  'nav-basket-button__price': string;
}
export const cssExports: CssExports;
export default cssExports;
