// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'products': string;
  'products-type': string;
}
export const cssExports: CssExports;
export default cssExports;
