// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty-basket': string;
  'empty-basket__description': string;
  'empty-basket__image': string;
  'empty-basket__return-button': string;
  'empty-basket__title': string;
}
export const cssExports: CssExports;
export default cssExports;
