// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'basket-button': string;
  'basket-footer': string;
  'basket-result': string;
  'basket-result__amount': string;
  'basket-result__price': string;
  'counter': string;
  'order': string;
  'return': string;
}
export const cssExports: CssExports;
export default cssExports;
