// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'basket-header': string;
  'basket-header__clear': string;
  'basket-header__title': string;
}
export const cssExports: CssExports;
export default cssExports;
