// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'round-button': string;
  'round-button_gray': string;
  'round-button_orange': string;
}
export const cssExports: CssExports;
export default cssExports;
