// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footer__content': string;
  'navigation-links': string;
  'navigation-links__item': string;
  'navigation-links__list': string;
}
export const cssExports: CssExports;
export default cssExports;
