// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main-page__content-list': string;
  'main-page__content-title': string;
}
export const cssExports: CssExports;
export default cssExports;
