// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-button': string;
  'action-button_gray': string;
  'action-button_orange': string;
}
export const cssExports: CssExports;
export default cssExports;
